export const SET_AUTHED_USER = "SET_AUTHED_USER",
  ADD_QUESTION = "ADD_QUESTION",
  GET_QUESTION = "GET_QUESTION",
  SET_ANSWER = "SET_ANSWER",
  GET_QUESTIONS = "GET_QUESTIONS",
  GET_USERS = "GET_USERS";
